### ISSUE TITLE
Could not resolve dependencies for project org.healthnlp:deepphe-ctakes-cancer:jar:0.0.1: Failure to find org.apache.ctakes:ctakes-temporal:jar:4.0.1-20171018.124842-54

### ISSUE THREAD

**Issue by luto65** [DeepPhe/DeepPhe-Release#1]
Dear DeepPhe,
after 
`git clone`

I moved in DeepPhe-Release and then

`mvn compile`

obtaining then the error in the subject line.

**Comment by seanfinan** [comment]
Hi Luto,

That dependency should be available.  Are you behind a firewall?

**Comment by harryhoch** [comment]
i can confirm that I just deleted ctakes-temporal from my .m2 repository and then ran without problems.

**Comment by luto65** [comment]
I confirm too, now it builds and runs and without problems. You can close this issue. thankyou

**Comment by seanfinan** [comment]
We cannot release with any firewall settings, but according to maven this should work:
https://maven.apache.org/guides/mini/guide-proxies.html
