### ISSUE TITLE
Build errors within Intellij

### ISSUE THREAD

**Issue by savo0014** [DeepPhe/DeepPhe-Release#10]
Getting errors when building within Intellij
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\episode\EvaluationOfDocumentLevelEpisodeLabel.java
    Error:Error:line (14)java: package org.apache.ctakes.cancer.type.textspan does not exist
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\episode\EvaluationOfEpisode.java
    Error:Error:line (16)java: package org.apache.ctakes.cancer.type.textspan does not exist
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\ae\EpisodeFeatureExtractorAe.java
    Error:Error:line (18)java: package org.apache.ctakes.cancer.type.textspan does not exist
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\ae\EpisodicDocumentAe.java
    Error:Error:line (17)java: package org.apache.ctakes.cancer.type.textspan does not exist
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\episode\EvaluationOfDocumentLevelEpisodeLabelMela.java
    Error:Error:line (14)java: package org.apache.ctakes.cancer.type.textspan does not exist
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\ae\DocEpisodeTagger.java
    Error:Error:line (5)java: package org.apache.ctakes.cancer.type.textspan does not exist
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\ae\EpisodicDocumentAeMela.java
    Error:Error:line (16)java: package org.apache.ctakes.cancer.type.textspan does not exist
C:\work\DeepPhe-Release\deepphe-ctakes-cancer\src\main\java\org\apache\ctakes\cancer\ae\EpisodeAnaforaXMLReader.java
    Error:Error:line (30)java: package org.apache.ctakes.cancer.type.textspan does not exist

**Comment by yuanzhou** [comment]
I compiled on Linux without using any IDE, and no error. Did you try to build in command line directly?

**Comment by jamesmasanz** [comment]
I'll try from within the IDE and post my observations

**Comment by savo0014** [comment]
I am able to compile from the command line.

**Comment by jamesmasanz** [comment]
using IntelliJ Community Edition 2017.3, after checking out the code, and importing maven profiles, I see the runJcasGen checkbox is checked.   I set the project SDK to 1.8 and then Run Maven Build on deepphe (root) Lifecycle compile, it builds successfully. I'll have to compare my steps to the documented ones.

![image](https://user-images.githubusercontent.com/26445243/47738753-2f0ef480-dc4a-11e8-800b-65647406a84d.png)

**Comment by savo0014** [comment]
this worked for me too, thank you, James! Before I ran the build from the Intellij dropdown (or Ctrl+F9). The GUI starts, it has three slots for parameter names -- input dir, output dir and domain. In the Quick Start manual, it says to expect:
Input Directory (with Notes/Reports) *
Output Directory (for Summary files) *
Ontology Name (for non-default specification)
Configuration Directory (for evaluation of results)

I don't see the last two in the GUI.

**Comment by jamesmasanz** [comment]
I  updated the Quick-Start page with instructions on how to start a compile so that jcasgen runs before the GUI opens
