### ISSUE TITLE
Output directory difference between main repo and release repo code

### ISSUE THREAD

**Issue by yuanzhou** [DeepPhe/DeepPhe-Release#12]
When I compiled using the main repo's code I always get the output folder contains the 4 sub folder:

![capture](https://user-images.githubusercontent.com/195873/47734932-c6237e80-dc41-11e8-856d-51edb1f67af4.PNG)

When I tested the release repo today, I only saw two of them. Is this the desired difference?

![capture22](https://user-images.githubusercontent.com/195873/47734987-e4897a00-dc41-11e8-8f0c-fbb89e81275f.PNG)

**Comment by savo0014** [comment]
I see only EMR_EVAL. I ran startGui within Intellij.

**Comment by seanfinan** [comment]
The two directories EMR_EVAL and output_graph are the desired outputs.  The other directories were used for debugging during development.

**Comment by yuanzhou** [comment]
Good to know, thanks for clarifying. Closing this issue.
