### ISSUE TITLE
could not connect to the dictionary db

### ISSUE THREAD

**Issue by savo0014** [DeepPhe/DeepPhe-Release#14]
When I ran the startGui after the first run finished, I get this error "could not reopen dabase..." after attempting to connect to the dabase for the dictionary lookup. I vaguely remember there was a file that locked the db and that needed to be removed after each run. Could remind me what the file was?

**Comment by seanfinan** [comment]
There is a lock file that is created during runs, but it should not need to be removed manually unless there is a problem.  If there is a lock then the next run should report such a case in the log and point to the lock file.  It is normally in resources/org/apache/ctakes/dictionary/lookup/fast/ncit_plus_16ab

**Comment by savo0014** [comment]
yes, there was a lck file in resources/org/apache/ctakes/dictionary/lookup/fast/ncit_plus_16ab. i removed manually and then re-ran without issues.

**Comment by seanfinan** [comment]
A shutdown hook should be added to Apache cTAKES to automatically clean up an hsql db lock file if there is a system failure.

**Comment by seanfinan** [comment]
Placed fix in Apache cTAKES.  See cTAKES jira item #526
https://issues.apache.org/jira/browse/CTAKES-526
