### ISSUE TITLE
DeepPhe GUI shows 3 parameters instead of 4

### ISSUE THREAD

**Issue by linflyer** [DeepPhe/DeepPhe-Release#15]
I start the GUI from the command line but don't see the 4th parameter setting: "Configuration Directory (for evaluation of results)”

**Comment by jamesmasanz** [comment]
Thanks Chen.  Sean fixed this (thanks Sean) - he updated the wiki page to remove mention of the now non-existent 4th parameter.

**Comment by linflyer** [comment]
Thanks!
