### ISSUE TITLE
clarification on neo4j

### ISSUE THREAD

**Issue by savo0014** [DeepPhe/DeepPhe-Release#16]
The quick start points to the neo4j webpage: https://neo4j.com/
The download button there takes you to the desktop and server options. How to configure the NEO4J_HOME? We would appreciate a bit more instruction on the Neo4j installation and configuration.

**Comment by savo0014** [comment]
instructions are here: https://github.com/DeepPhe/DeepPhe-Viz/blob/master/README.md

**Comment by yuanzhou** [comment]
Here is the link to neo4j installation: https://neo4j.com/docs/operations-manual/current/installation/

I don't think the Viz tool instructions should cover the neo4j installation.

**Comment by yuanzhou** [comment]
OK, I've added the neo4j download screenshot as well as link to their installation instructions.

**Comment by jamesmasanz** [comment]
closing since the documentation has been updated and Zhou isn't in the list of people who can be assigned to.
