### ISSUE TITLE
unzipping bin.zip shows different folder names than what the instruction says

### ISSUE THREAD

**Issue by linflyer** [DeepPhe/DeepPhe-Release#17]
I unzip the deepphe-0.2.0-bin.zip, I have a directory named "deepphe-0.2.0" and within that directory, I found a bin folder. Not as the instruction says, "After unzipping, you will have a directory named deepphe-0.2.0-bin and within that directory another named deepphe-0.2.0.”

**Comment by seanfinan** [comment]
This is actually system-specific.  On windows an unzip will/can create a container directory named after the zip file.  The unix/linux tools do not typically create this container dir (deepphe-0.2.0-bin).  The documentation has been updated to denote that both possibilities exist.

**Comment by linflyer** [comment]
Thanks!
