### ISSUE TITLE
Need instructions on installing Neo4j

### ISSUE THREAD

**Issue by linflyer** [DeepPhe/DeepPhe-Release#18]
I installed Neo4J Desktop version and Neo4j Enterprise Edition for Developers. Should I download Neo4J server and drivers? How to configure the NEO4J_HOME? I would appreciate a little instruction on the Neo4j installation and configuration. 0.”

**Comment by savo0014** [comment]
instructions are here: https://github.com/DeepPhe/DeepPhe-Viz/blob/master/README.md

**Comment by yuanzhou** [comment]
@linflyer you can just download the neo4j community server 3.2.13: https://neo4j.com/download-center/#releases

Just unzip the downloaded file and there's no installer needed. Then change directory to the top-level extracted directory.

Run `bin\neo4j console`

You may need to run the command in windows administrative mode if there's any permission issues. If not, then it should work. I had to no need to configure NEO4J_HOME.

**Comment by jamesmasanz** [comment]
closing this - received email that the install finished successfully.
