### ISSUE TITLE
Cannot run pipeline twice in cTakes Piper File Submitter

### ISSUE THREAD

**Issue by seanfinan** [DeepPhe/DeepPhe-Release#19]
Running once in the gui works.  If you change settings and run again or keep the same settings and run again the second run fails.

This is because the PatientSummarizer engine tries to register itself again for the second run.  Registering an engine under the same name is an error and the pipeline quits.  This is an Apache cTAKES feature.

**Comment by savo0014** [comment]
i think this is because of the lck file in resources/org/apache/ctakes/dictionary/lookup/fast/ncit_plus_16ab. When I remove the lck file I am able to restart. I hope it addresses the same issue that Sean meant.

**Comment by seanfinan** [comment]
This is a different problem.  I identify the cause in the first comment above:
This is because the PatientSummarizer engine tries to register itself again for the second run. Registering an engine under the same name is an error and the pipeline quits. This is an Apache cTAKES feature.

**Comment by seanfinan** [comment]
Added a note to the documentation that the gui can only run the pipeline once.
