### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by luto65** [DeepPhe/DeepPhe-Release#2]
would it be possible to have a Dockerfile for an easy installation / deployment ?

**Comment by savo0014** [comment]
Thank you for your interest in DeepPhe. Could you please introduce yourself?
--
Guergana Savova, PhD, FACMI
Associate Professor
PI Natural Language Processing Lab
Boston Children's Hospital and Harvard Medical School
300 Longwood Avenue
Mailstop: BCH3092
Enders 144.1
Boston, MA 02115
Tel: (617) 919-2972
Fax: (617) 730-0817
Guergana.Savova@childrens.harvard.edu<mailto:Guergana.Savova@childrens.harvard.edu>
Harvard Scholar: http://scholar.harvard.edu/guergana_k_savova/biocv
http://ctakes.apache.org<http://ctakes.apache.org/>
http://thyme.healthnlp.org<http://thyme.healthnlp.org/>
http://cancer.healthnlp.org<http://cancer.healthnlp.org/>
http://share.healthnlp.org<http://share.healthnlp.org/>
http://center.healthnlp.org<http://center.healthnlp.org/>

**Comment by agarfau** [comment]
Hi!
Is there any update on the Dockerization of the project? I saw there's another repo but seems like a work in progress. Any info would be appreciated.

Thanks!
