### ISSUE TITLE
neo4j versions

### ISSUE THREAD

**Issue by harryhoch** [DeepPhe/DeepPhe-Release#20]
I forget the exact 3.2x. version, perhaps it was 13, but we should note that it runs into trouble on the new OS X mojave. Folks using Mojave might need to run a virtual machine instead.  This should probably be addressed in the Quick Start notes

**Comment by jamesmasanz** [comment]
Do you remember where you heard about that issue? I didn't see it in the neo4j issues list or in a quick google search

**Comment by harryhoch** [comment]
I ran into this problem when I tried to run it myself. I can't try it here, as I have no Mojave system handy. might be able to replicate it tonight.

**Comment by seanfinan** [comment]
I think that, rather than listing (and testing) every combination of what doesn't work, it would be better to list the versions and systems upon which we have successfully run.

**Comment by fedorov** [comment]
I am on Mojave, and I didn't run into trouble yet (or maybe I did not realize I ran into trouble) using the 3.2.13 version of neo4j as prescribed in the documentation. 

@harryhoch what kind of trouble did you experience?

**Comment by harryhoch** [comment]
@federov, honestly, I don't remember.  I know that I've got it running on one of my two machines. Probably just user error at this point.
