### ISSUE TITLE
structure of input data files

### ISSUE THREAD

**Issue by harryhoch** [DeepPhe/DeepPhe-Release#21]
Quick Start notes should be updated to describe the file structure needed for the notes input directory

ie, if the directory $DIR is specified for input,  that directory should have one subdiretory for each patient, containing all of the notes for that patient.

**Comment by jamesmasanz** [comment]
Thanks Harry. I'll make that update today.

**Comment by jamesmasanz** [comment]
Added mention of subdirs. I also fixed the description of Input Directory on 
https://github.com/DeepPhe/DeepPhe-Release/wiki/Input-and-Output-Directories
