### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by harryhoch** [DeepPhe/DeepPhe-Release#22]
might be good to add something to the documentation indicating the possibility that processing documents can take a fair amount of time...

**Comment by fedorov** [comment]
As a reference point, it took 4 minutes to parse 41 pathology report on a system below

![image](https://user-images.githubusercontent.com/313942/50650493-96993700-0f4e-11e9-807e-db595dc433f4.png)

**Comment by fedorov** [comment]
On a related note, it would be helpful if upon completion there was a log entry saying how long processing took.

**Comment by seanfinan** [comment]
Hi Andrey,


There is in the current unreleased version.  It reports initialization and total processing time, plus average time per document.

________________________________

**Comment by fedorov** [comment]
Would be great to have some progress reporting (like percent of the documents processed). I've been running the pipeline for about 1.5 hours now with 2000+ documents, and really have no clue when it will be finished. Maybe this deserves a separate issue, but it is related to the current closed one.

**Comment by seanfinan** [comment]
Progress reporting is also (mostly) part of the 3rd party gui library.  However, since I am a contributor to said software ... I just checked in an enhancement that include a progress bar at the top of the gui with text "[current#] / [total#]" in the bar.  It should appear in the next version.
