### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by harryhoch** [DeepPhe/DeepPhe-Release#23]
OS X - 

harryh-mdt:DeepPhe-Release harry$ java -version
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

mvn clean package -Dmaven.test.skip=true

[ERROR] /Users/harry/Downloads/DeepPhe-Release/deepphe-ctakes-cancer/src/main/java/org/apache/ctakes/cancer/cr/Hl7Reader.java:[450,47] cannot find symbol
  symbol:   method getDescendentFiles(java.io.File,java.util.List<java.lang.String>)
  location: class org.apache.ctakes.cancer.cr.Hl7Reader
[INFO] 1 error

also true with java build 18.3

**Comment by seanfinan** [comment]
Visibility of a 3rd party library method changed and the main() method of Hl7Reader no longer compiled.  The main() is not needed and has been commented out.
