### ISSUE TITLE
Broken link in the documentation

### ISSUE THREAD

**Issue by fedorov** [DeepPhe/DeepPhe-Release#24]
Just fyi, on this page https://github.com/DeepPhe/DeepPhe-Release/wiki/DeepPhe-Output this link https://github.com/DeepPhe/DeepPhe/wiki/Quick-Start#output-data-in-neo4j is invalid. I think the correct link should be https://github.com/DeepPhe/DeepPhe-Release/wiki/Quick-Start#view-data-with-deepphe-viz.

**Comment by seanfinan** [comment]
This should now be working.
