### ISSUE TITLE
PatientX Gold annotations are incorrect.

### ISSUE THREAD

**Issue by seanfinan** [DeepPhe/DeepPhe-Release#3]
Gold annotations in data/sample/eval/ do not use the correct ontology class names.  Evaluation of patientX produces:

-----------------------------------------------------------------------------------------
Label                      	TP    	TP'		FP	FN	TN	Precis	Recall	Accur	F1-Score
Cancer                     	0.0000	0		2	1	0	0.0000	0.0000	0.0000	   -  

-----------------------------------------------------------------------------------------
Label                                 	TP    	TP'		FP	FN	TN	Precis	Recall	Accur	F1-Score
Tumor                                 	0.0000	0		4	2	0	0.0000	0.0000	0.0000	   -  

As the distributed test set the eval should produce something above 0.0000   Manual evaluation shows that the score should be better.

**Comment by jamesmasanz** [comment]
updated gold files will be checked in Monday 10/29
