### ISSUE TITLE
Error in downloading DeepPhe-lib.zip

### ISSUE THREAD

**Issue by shohrehhd** [DeepPhe/DeepPhe-Release#38]
Hello,

I am trying to install DeepPhe, but the link to the [lib file](https://github.com/DeepPhe/DeepPhe-Dist/releases/download/main/DeepPhe-lib.zip) fails.

**Comment by seanfinan** [comment]
Hi shohrehdd,
Can you provide some details on your workflow?  That link does exist and a file will be downloaded.  Are you trying to download it directly, or are you using our installer tool?  Using the tool is the preferred method for installing DeepPhe.  https://deepphe.github.io/

**Comment by shohrehhd** [comment]
I am using the tool, while running the installer I get the following error:
![Screenshot 2024-02-08 at 2 35 31 PM](https://github.com/DeepPhe/DeepPhe-Release/assets/72942590/5958594c-cbca-4762-9aad-6ec9c02a5c27)

**Comment by seanfinan** [comment]
Are you behind a firewall, possibly one enforced by a workplace?   If you type that link into a web browser does it download the file?  It is a large file, so a slow or otherwise impaired internet connection may timeout if it cannot download the file within some time limit.

**Comment by shohrehhd** [comment]
That was indeed the case! thank you!
