### ISSUE TITLE
Update release version in pom for deepphe-distribution binary Installation

### ISSUE THREAD

**Issue by yuanzhou** [DeepPhe/DeepPhe-Release#8]
When I tested with building the binary installation, the generated zip and jar still has -0.0.1-SNAPSHOT. Need to update to the 0.2.0 release version.

**Comment by seanfinan** [comment]
I cannot duplicate this problem.  I have also triple-checked the versions in the pom files and they all look correct.

**Comment by yuanzhou** [comment]
https://github.com/DeepPhe/DeepPhe/blob/master/deepphe-distribution/pom.xml#L7

I think I used the main repo's code.
