### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by yuanzhou** [DeepPhe/DeepPhe-Release#9]
The following directories need to be added to the `.gitignore`:

- deepphe-neo4j/target/
- deepphe-viz-neo4j/target/

I also had the following two files generated, not sure if we should add the files or directories to `.gitignore`.

- resources/org/apache/ctakes/dictionary/lookup/fast/ncit_plus_16ab/ncit_plus_16ab.lck
- resources/org/apache/ctakes/dictionary/lookup/fast/ncit_plus_16ab/ncit_plus_16ab.log

**Comment by seanfinan** [comment]
The target directories should not have been a problem, but I added a second line to .gitignore for them.  I also added a line to ignore everything under resources/
